// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lewndswbiohfhlogxqev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxld25kc3diaW9oZmhsb2d4cWV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDM2MDcsImV4cCI6MjA2NTUxOTYwN30.zPzmmGic-Z1Yemo9x8qu6-K-i_dE8Q7I5lyzydzyubk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);